name: CasinoCore
version: '${version}'
main: io.wax100.casinoCore.CasinoCore
api-version: '1.20'
authors: [wax100]
description: カジノプラグイン - チップ売買・換金・ランキング
depend: [Vault, ChipLib]

commands:
  casino:
    description: カジノモードの管理コマンド
    usage: /casino <on|off|status|ranking|stats>


permissions:
  casino.admin:
    description: カジノモードの管理権限
    default: op

